FROM python:3.10-slim

RUN addgroup appuser && adduser -S -G appuser appuser

WORKDIR /app
COPY . .

RUN pip install pipenv
RUN pipenv requirements
RUN pip install --no-cache-dir -r requirements.txt

USER appuser

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]