FROM python:3.10-slim

RUN adduser --system --group appuser

WORKDIR /app
COPY . .

RUN pip install pipenv
RUN pipenv requirements --dev > requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pytest

USER appuser

EXPOSE 5000

CMD ["flask", "--debug", "run", "--host=0.0.0.0"]

# run with: docker compose up