FROM python:3.10-slim

RUN adduser --system --group appuser

WORKDIR /app
COPY . .

RUN pip install pipenv
RUN pipenv requirements > requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

USER appuser

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app", "--timeout", "200", "--log-file", "-"]