# List is alphabetical based on print out for G.nodes() - Zones added manually.


map_ctz = {
    "Abah's Landing": "Hew's Bane",
    "Alinor": "Summerset",
    "Alten Corimont": "Shadowfen",
    "Anvil": "Gold Coast",
    "Balmora": "Vvardenfell",
    "Belkarth": "Craglorn",
    "Betnikh": "Betnikh",
    "Bleakrock Village": "Bleakrock Isle",
    "Daggerfall": "Glenumbra",
    "Davon's Watch": "Stonefalls",
    "Dhalmora": "Bal Foyen",
    "Elden Root": "Grahtwood",
    "Evermore": "Bangkorai",
    "Gnisis": "Vvardenfell",
    "Haven": "Grahtwood",
    "Eagle's Strand": "Khenarthi's Roost",
    "Lilmoth": "Murkmire",
    "Molag Mar": "Vvardenfell",
    "Mournhold": "Deshaan",
    "Orsinium": "Wrothgar",
    "Rawl'kha": "Reaper's March",
    "Riften": "The Rift",
    "Rimmen": "Northern Elsweyr",
    "Sadrith Mora": "Vvardenfell",
    "Sentinel": "Alik'r Desert",
    "Seyda Neen": "Vvardenfell",
    "Shimmerene": "Summerset",
    "Shornhelm": "Rivenspire",
    "Skywatch": "Auridon",
    "Stormhold": "Shadowfen",
    "Port Hunding": "Stros M'Kai",
    "Suran": "Vvardenfell",
    "Tel Mora": "Vvardenfell",
    "Vivec": "Vvardenfell",
    "Vulkhel Guard": "Auridon",
    "Vulkwasten": "Malabal Tor",
    "Wayrest": "Stormhaven",
    "Windhelm": "Eastmarch",
    "Woodhearth": "Greenshade",
}

# print(cities_to_zones["Tel Mora"])
