locations = [
    "Balmora",
    "Gnisis",
    "Vivec",
    "Molag Mar",
    "Suran",
    "Tel Mora",
    "Seyda Neen",
    "Vulkhel Guard",
    "Khenarthi's Roost",
    "Skywatch",
    "Haven",
    "Daggerfall",
    "Stros M'Kai",
    "Betnikh",
    "Wayrest",
    "Sentinel",
    "Bleakrock Isle",
    "Davon's Watch",
    "Dhalmora",
    "Alten Corimont",
    "Windhelm",
    "Abah's Landing",
    "Woodhearth",
    "Anvil",
    "Shimmerene",
    "Murkmire",
    "Mournhold",
    "Elden Root",
    "Rawl'kha",
    "Vulkwasten",
    "Shornhelm",
    "Stormhold",
    "Evermore",
    "Riften",
    "Sadrith Mora",
    "Alinor",
    "Orsinium",
    "Vulhkel Guard",
    "Belkarth",
]

locations = sorted(locations)
